# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-08 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='消耗量')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='used_resource',
        ),
        migrations.AddField(
            model_name='dishres',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinner.Dish'),
        ),
        migrations.AddField(
            model_name='dishres',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinner.ResourceType'),
        ),
    ]
