# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-08 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_auto_20200408_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dsp',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='dish',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='单位'),
        ),
    ]
