# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0003_auto_20200408_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='kind',
            field=models.IntegerField(choices=[(0, '未分类'), (1, '热菜'), (2, '冷菜'), (3, '汤'), (4, '酒水'), (5, '小吃')], default=0, verbose_name='种类'),
        ),
    ]
