# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-13 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0004_dish_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='关键字')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='key_word',
            field=models.CharField(blank=True, max_length=300, verbose_name='关键字'),
        ),
    ]
